# Generated by Django 5.2.6 on 2025-09-17 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SukuCadang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('jumlah_stok', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_produksi', models.PositiveIntegerField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('proses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.proses')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('Masuk', 'Masuk'), ('Keluar', 'Keluar')], max_length=10)),
                ('tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_pengguna', models.CharField(max_length=150)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('suku_cadang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.sukucadang')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stasiun', models.CharField(max_length=50)),
                ('id_tool', models.CharField(max_length=50, unique=True, verbose_name='ID Tool')),
                ('tipe_tool', models.CharField(max_length=100, verbose_name='Tipe Tool')),
                ('nomor_seri', models.CharField(max_length=100, verbose_name='Nomor Seri')),
                ('jumlah_shot', models.IntegerField(default=1, verbose_name='Shot per Produksi')),
                ('max_shot', models.IntegerField(default=0, verbose_name='Max Shot')),
                ('shot_terpakai', models.IntegerField(default=0, verbose_name='Shot Terpakai')),
                ('lifetime', models.IntegerField(default=365, verbose_name='Lifetime (hari)')),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipakai', 'Dipakai'), ('Perbaikan', 'Dalam Perbaikan')], default='Tersedia', max_length=20)),
                ('jenis_kerusakan', models.CharField(blank=True, help_text='Diisi saat tool masuk lab', max_length=255, null=True)),
                ('part_yang_digunakan', models.TextField(blank=True, help_text='Part yang diganti atau diperbaiki', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('proses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.proses')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPerbaikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Sedang Diperbaiki', 'Sedang Diperbaiki'), ('Selesai', 'Selesai')], default='Sedang Diperbaiki', max_length=20)),
                ('waktu_masuk', models.DateTimeField()),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('jenis_kerusakan', models.CharField(blank=True, max_length=255, null=True)),
                ('part_yang_digunakan', models.TextField(blank=True, null=True)),
                ('dikerjakan_oleh', models.CharField(blank=True, max_length=150, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_perbaikan', to='tracker.tool')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('is_developer', models.BooleanField(default=False)),
                ('can_view_proses', models.BooleanField(default=False, verbose_name='Akses Menu Proses & Tools')),
                ('can_view_lab', models.BooleanField(default=False, verbose_name='Akses Menu Lab Maintenance')),
                ('can_view_stok', models.BooleanField(default=False, verbose_name='Akses Menu Stok Suku Cadang')),
                ('can_view_laporan', models.BooleanField(default=False, verbose_name='Akses Menu Laporan')),
                ('can_view_produksi', models.BooleanField(default=False, verbose_name='Akses Menu Target Produksi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
