# Generated by Django 5.2.6 on 2025-09-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionlog',
            name='proses',
        ),
    ]
