# Generated by Django 5.2.6 on 2025-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatgudang',
            name='proses_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riwayatgudang',
            name='stasiun_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
