# Generated by Django 5.2.6 on 2025-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_productionlog_proses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_lab',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Lab'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_laporan',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Laporan (Termasuk Download)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_produksi',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Produksi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_proses',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Proses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_stok',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Stok'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_lab',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Lab'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_laporan',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Laporan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_produksi',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Produksi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_proses',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Proses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_view_stok',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Stok'),
        ),
    ]
