# Generated by Django 5.2.6 on 2025-09-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_userprofile_can_edit_lab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='jam_pakai_terakumulasi',
            field=models.FloatField(default=0, verbose_name='Jam Pakai Terakumulasi'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='lifetime',
            field=models.IntegerField(default=5000, verbose_name='Total Jam Pakai Maksimal'),
        ),
    ]
