# Generated by Django 5.2.6 on 2025-10-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tool_jam_pakai_terakumulasi_alter_tool_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipakai', 'Dipakai'), ('Perbaikan', 'Dalam Perbaikan'), ('Gudang TPM', 'Gudang TPM')], default='Tersedia', max_length=20),
        ),
    ]
