# Generated by Django 5.2.6 on 2025-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_tool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='deskripsi',
            field=models.TextField(default='Belum ada deskripsi'),
        ),
        migrations.AddField(
            model_name='tool',
            name='nama',
            field=models.CharField(default='Tanpa Nama', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('arsip', 'Arsip')], default='aktif', max_length=20),
        ),
    ]
