# Generated by Django 5.2.6 on 2025-10-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_tool_deskripsi_tool_nama_alter_tool_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('gudang', 'Gudang TPM'), ('arsip', 'Arsip'), ('perbaikan', 'Dalam Perbaikan')], default='aktif', max_length=20),
        ),
    ]
