# Generated by Django 5.2.6 on 2025-10-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_tool_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('gudang', 'Gudang TPM'), ('arsip', 'Arsip'), ('perbaikan', 'Dalam Perbaikan'), ('tersedia', 'Tersedia'), ('dipakai', 'Dipakai')], default='aktif', max_length=20),
        ),
    ]
