# Generated by Django 5.2.6 on 2025-10-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_tool_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('arsip', 'Arsip'), ('tersedia', 'Tersedia'), ('dipakai', 'Dipakai'), ('perbaikan', 'Dalam Perbaikan'), ('gudang_tpm', 'Gudang TPM')], default='aktif', max_length=20),
        ),
    ]
