# Generated by Django 5.2.6 on 2025-10-08 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_tool_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='nama',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_gudang_tpm',
            field=models.BooleanField(default=False, verbose_name='Akses Penuh Menu Gudang TPM'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_gudang_tpm',
            field=models.BooleanField(default=False, verbose_name='Lihat Menu Gudang TPM'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipakai', 'Dipakai'), ('Perbaikan', 'Dalam Perbaikan'), ('Gudang TPM', 'Gudang TPM')], default='Tersedia', max_length=20),
        ),
        migrations.CreateModel(
            name='RiwayatGudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id_snapshot', models.CharField(blank=True, max_length=50)),
                ('tipe_tool_snapshot', models.CharField(blank=True, max_length=100)),
                ('nomor_seri_snapshot', models.CharField(blank=True, max_length=100)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_gudang', to='tracker.tool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
