# Generated by Django 5.2.6 on 2025-10-08 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_remove_tool_deskripsi_remove_tool_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_edit_gudang_tpm',
            new_name='can_manage_gudang_tpm',
        ),
    ]
