# Generated by Django 5.2.6 on 2025-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_rename_can_edit_gudang_tpm_userprofile_can_manage_gudang_tpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_gudang_tpm',
            field=models.BooleanField(default=False, verbose_name='Dapat Mengelola Gudang TPM'),
        ),
    ]
