# Generated by Django 5.2.6 on 2025-10-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_userprofile_can_manage_gudang_tpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_view_gudang_tpm',
        ),
        migrations.DeleteModel(
            name='RiwayatGudang',
        ),
    ]
