# Generated by Django 5.2.6 on 2025-10-09 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_remove_userprofile_can_view_gudang_tpm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatGudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tool_id_snapshot', models.CharField(max_length=100)),
                ('tipe_tool_snapshot', models.CharField(max_length=100)),
                ('nomor_seri_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_gudang', to='tracker.tool')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
